// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Create a safe client that handles connection errors gracefully
let supabaseClient: any;

// Mock data for when backend is unavailable
const mockData = {
  services: [
    { id: "1", name: "Locs Maintenance", description: "Professional locs cleaning", duration_minutes: 120, price: 45.00, is_active: true, created_at: new Date().toISOString() },
    { id: "2", name: "Locs Retwist", description: "Root maintenance and retwisting", duration_minutes: 90, price: 35.00, is_active: true, created_at: new Date().toISOString() },
    { id: "3", name: "Beard Trim", description: "Professional beard trimming", duration_minutes: 30, price: 15.00, is_active: true, created_at: new Date().toISOString() },
    { id: "4", name: "Hair Cut", description: "Classic haircut and styling", duration_minutes: 45, price: 25.00, is_active: true, created_at: new Date().toISOString() }
  ],
  professionals: [
    { id: "1", name: "Adisco", title: "Master Locs Stylist", bio: "Specialist in locs maintenance with over 10 years of experience", is_active: true },
    { id: "2", name: "Marcus", title: "Barber & Stylist", bio: "Expert in modern cuts and traditional barbering techniques", is_active: true }
  ],
  bookings: [],
  users: []
};

// Create fallback client that doesn't throw errors
const createSafeClient = () => {
  try {
    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_URL.includes('your-project-id')) {
      throw new Error('Invalid credentials');
    }
    return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } catch (error) {
    console.log('Using offline mode - backend not available');
    return createMockClient();
  }
};

// Mock client that returns sample data
const createMockClient = () => ({
  from: (table: string) => ({
    select: (columns?: string) => ({
      eq: (column: string, value: any) => ({
        maybeSingle: () => Promise.resolve({ data: null, error: null }),
        single: () => Promise.resolve({ data: null, error: null }),
        order: (col: string, opts?: any) => Promise.resolve({ data: mockData[table as keyof typeof mockData] || [], error: null }),
        then: (callback: any) => callback({ data: mockData[table as keyof typeof mockData] || [], error: null })
      }),
      order: (column: string, options?: any) => Promise.resolve({ data: mockData[table as keyof typeof mockData] || [], error: null }),
      then: (callback: any) => callback({ data: mockData[table as keyof typeof mockData] || [], error: null, count: (mockData[table as keyof typeof mockData] || []).length })
    }),
    insert: (data: any) => Promise.resolve({ data, error: null }),
    update: (data: any) => ({
      eq: (column: string, value: any) => Promise.resolve({ data, error: null })
    })
  }),
  auth: {
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    onAuthStateChange: (callback: any) => {
      // Call callback immediately with no session
      setTimeout(() => callback('SIGNED_OUT', null), 100);
      return { data: { subscription: { unsubscribe: () => {} } } };
    },
    signOut: () => Promise.resolve({ error: null }),
    signUp: (credentials: any) => Promise.resolve({ 
      data: { user: null, session: null }, 
      error: { message: "Demo mode - signup not available" } 
    }),
    signInWithPassword: (credentials: any) => Promise.resolve({ 
      data: { user: null, session: null }, 
      error: { message: "Demo mode - please check backend connection" } 
    })
  }
});

export const supabase = createSafeClient();